//Benzor Iron Weapon 6 - Consigue empleo 20%

/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (d100()>20) return FALSE;

return TRUE;
}

