//LilaMalcolm5 - Lila ve q no entregaste la carta aun

/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

#include "nw_i0_tool"

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!CheckPartyForItem(oPC, "CartaLilaMalcolm")) return FALSE;

return TRUE;
}


