//MalcolmLila1 - 25% de posibilidades q Malcolm tenga una carta escrita para su hermana.

/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (d100()>25) return FALSE;

return TRUE;
}

