const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_10_PERCENT = 10;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_20_PERCENT = 11;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_30_PERCENT = 12;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_40_PERCENT = 13;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_50_PERCENT = 14;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_60_PERCENT = 15;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_70_PERCENT = 16;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_80_PERCENT = 17;
const int IP_CONST_IMMUNITYMISC_CRITICAL_HITS_90_PERCENT = 18;

const int IP_CONST_FEAT_IMPROVED_TWO_WEAPON_FIGHTING = 601;
const int IP_CONST_FEAT_GREATER_TWO_WEAPON_FIGHTING  = 602;
const int IP_CONST_FEAT_MANYSHOT                     = 603;
const int IP_CONST_FEAT_PINPOINT_ACCURACY            = 604;
const int IP_CONST_FEAT_PERFECT_SHOT                 = 605;
